apiVersion: v1
kind: Service
metadata:
  name: db_task_manager
  namespace: dev
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: db_task_manager
  ports:
    - port: 3306
      targetPort: 3306
      Protocol: TCP
