services:

  task-manager-backend:
    image: task-manager-backend:${task_manager_backend}

    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - CORS_ALLOWED_ORIGINS=http://54.254.120.73:5173
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - task-manager-network
    restart:  always
    depends_on:
      - db-task-manager

  db-task-manager:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: nikhil@12345
    ports:
      - "3306:3306"
    networks:
      - task-manager-network
    volumes:
      - task-manager-db:/var/lib/mysql
    restart: always

  task-manager-frontend:
    image: task-manager-frontend:${task_manager_frontend}

    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://54.254.120.73:8000/api
    ports:
      - "5173:80"
    networks:
      - task-manager-network
    restart:  always
    depends_on:
      - task-manager-backend
  
volumes:
  task-manager-db:

networks:
  task-manager-network:
    driver: bridge


