pipeline {
    
    agent {
        label "task-manager"
    }
    
    triggers {
        pollSCM ("* * * * *")
    }

    stages {
        stage ("git checkout") {
            steps {
                git url: "https://github.com/opsbyNikhil/task-manager.git",
                    branch: "dev"
            }
        }
    }
}