pipeline {
    
    agent {
        label "task-manager"
    }
    
    triggers {
        pollSCM ("* * * * *")
    }

    stages {
        stage ("git checkout") {
            steps {
                git url: "https://github.com/opsbyNikhil/task-manager.git",
                    branch: "dev"
            }
        }

        stage ("Install Dependencies") {
            steps {
                sh """
                python3 -m venv venv
                . venv/bin/activate
                pip install -r backend/requirements.txt
                """
            }
        }

    }
}