pipeline {
    environment {
        SECRET_KEY = credentials('SECRET_KEY')
        RESEND_API_KEY = credentials('RESEND_API_KEY')
        DB_PASSWORD = credentials('DB_PASSWORD')
        AWS_ACCESS_KEY_ID = credentials("AWS_ACCESS_KEY_ID")
        AWS_SECRET_ACCESS_KEY = credentials("AWS_SECRET_ACCESS_KEY")
        AWS_ACCOUNT_ID = credentials("AWS_ACCOUNT_ID")
        AWS_REGION = credentials("AWS_REGION")
        AWS_REPOSITORY = credentials("AWS_REPOSITORY")
        task_manager_backend = "${BUILD_NUMBER}"

    }
    
    agent {
        label "task-manager"
    }
    
    triggers {
        pollSCM ("* * * * *")
    }

    stages {

        stage ("git checkout") {
            steps {
                git url: "https://github.com/opsbyNikhil/task-manager.git",
                    branch: "dev"
            }
        }

        stage ("Install Dependencies") {
            steps {
                dir ("backend") {
                    sh """
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    """
                }
            }
        }

        stage ("Run Tests") {
            steps {
                dir ("backend") {
                    withCredentials([
                        string(
                            credentialsId: 'SECRET_KEY',
                            variable: 'SECRET_KEY'
                        ),
                        string(
                            credentialsId: 'RESEND_API_KEY',
                            variable: 'RESEND_API_KEY'
                        ),
                    ]) 
                    {
                        withEnv([
                            'CORS_ALLOWED_ORIGINS=http://localhost:5173'
                        ]) {
                            sh """
                                if [ -z "$SECRET_KEY" ]; then
                                    echo "SECRET_KEY is NOT available"
                                    exit 1
                                else
                                    echo "SECRET_KEY is available"
                                fi

                                if [ -z "$RESEND_API_KEY" ]; then
                                    echo "RESEND_API_KEY is NOT available"
                                    exit 1
                                else
                                    echo "RESEND_API_KEY is available"
                                fi

                                . venv/bin/activate
                                python manage.py test
                            """
                        }    
                    }
                }
            }
        }

        stage ("Sonarqube scan") {
            steps {
                dir ("backend") {
                    withCredentials([
                        string(
                            credentialsId: "SONAR_ID",
                            variable: "SONAR_TOKEN"
                    )]){
                        script {
                            def scannerhome = tool "SONAR_ID"
                            withSonarQubeEnv("SONAR_ID") {
                                sh """
                                    ${scannerhome}/bin/sonar-scanner \
                                        -Dsonar.projectKey=opsbyNikhil_task-manager \
                                        -Dsonar.organization=opsbynikhil \
                                        -Dsonar.host.url=https://sonarcloud.io \
                                        -Dsonar.login=$SONAR_TOKEN
                                """
                        }
                    }     
                    }
                }
            }
        }

        stage ("Docker Image") {
            steps {
                dir ("backend") {
                    sh '''docker compose build task-manager-backend'''
                }
            }
        }

        stage ("Push Docker Image to ECR") {
            steps {
                dir ("backend") {
                    withCredentials([
                        string(
                            credentialsId: "AWS_ACCESS_KEY_ID",
                            variable: "AWS_ACCESS_KEY_ID"
                        ),
                        string(
                            credentialsId: "AWS_SECRET_ACCESS_KEY",
                            variable: "AWS_SECRET_ACCESS_KEY"
                        ),
                        string(
                            credentialsId: "AWS_ACCOUNT_ID",
                            variable: "AWS_ACCOUNT_ID"
                        ),
                        string(
                            credentialsId: "AWS_REGION",
                            variable: "AWS_REGION"
                        ),
                        string(
                            credentialsId: "AWS_REPOSITORY",
                            variable: "AWS_REPOSITORY"
                        ),
                    ]){
                        sh """
                            echo "Logging in to Amazon ECR"
                            aws ecr get-login-password \
                                --region "$AWS_REGION" | \
                            docker login \
                                --username AWS \
                                --password-stdin \
                            "$AWS_ACCOUNT_ID".dkr.ecr."$AWS_REGION".amazonaws.com

                            echo "Tagging Docker Image"
                            docker tag \
                            task-manager-backend:$task_manager_backend \
                            "$AWS_ACCOUNT_ID".dkr.ecr."$AWS_REGION".amazonaws.com/task-manager-backend:$task_manager_backend

                            echo "Docker Push"
                            docker push \
                            "$AWS_ACCOUNT_ID".dkr.ecr."$AWS_REGION".amazonaws.com/task-manager-backend:$task_manager_backend
                        """ 
                    }
                }
            }
        }
    }
}