pipeline {
    environment {
        SECRET_KEY = credentials('SECRET_KEY')
        RESEND_API_KEY = credentials('RESEND_API_KEY')
        DB_PASSWORD = credentials('DB_PASSWORD')
        AWS_ACCESS_KEY_ID = credentials("AWS_ACCESS_KEY_ID")
        AWS_SECRET_ACCESS_KEY = credentials("AWS_SECRET_ACCESS_KEY")
        AWS_ACCOUNT_ID = credentials("AWS_ACCOUNT_ID")
        AWS_REGION = credentials("AWS_REGION")
        AWS_REPOSITORY = credentials("AWS_REPOSITORY")
        task_manager_backend = "${BUILD_NUMBER}"
        GITOPS_CREDENTIALS = "task-manager-backend-cd-github"
    }
    
    agent {
        label "task-manager"
    }
    
    triggers {
        pollSCM ("* * * * *")
    }

    stages {

        stage ("git checkout") {
            steps {
                git url: "https://github.com/opsbyNikhil/task-manager.git",
                    branch: "dev"
            }
        }

        stage ("Install Dependencies") {
            steps {
                dir ("backend") {
                    sh """
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    """
                }
            }
        }

        stage ("Run Tests") {
            steps {
                dir ("backend") {
                    withCredentials([
                        string(
                            credentialsId: 'SECRET_KEY',
                            variable: 'SECRET_KEY'
                        ),
                        string(
                            credentialsId: 'RESEND_API_KEY',
                            variable: 'RESEND_API_KEY'
                        ),
                    ]) 
                    {
                        withEnv([
                            'CORS_ALLOWED_ORIGINS=http://localhost:5173'
                        ]) {
                            sh """
                                if [ -z "$SECRET_KEY" ]; then
                                    echo "SECRET_KEY is NOT available"
                                    exit 1
                                else
                                    echo "SECRET_KEY is available"
                                fi

                                if [ -z "$RESEND_API_KEY" ]; then
                                    echo "RESEND_API_KEY is NOT available"
                                    exit 1
                                else
                                    echo "RESEND_API_KEY is available"
                                fi

                                . venv/bin/activate
                                python manage.py test
                            """
                        }    
                    }
                }
            }
        }

        stage ("Sonarqube scan") {
            steps {
                dir ("backend") {
                    withCredentials([
                        string(
                            credentialsId: "SONAR_ID",
                            variable: "SONAR_TOKEN"
                    )]){
                        script {
                            def scannerhome = tool "SONAR_ID"
                            withSonarQubeEnv("SONAR_ID") {
                                sh """
                                    ${scannerhome}/bin/sonar-scanner \
                                        -Dsonar.projectKey=opsbyNikhil_task-manager \
                                        -Dsonar.organization=opsbynikhil \
                                        -Dsonar.host.url=https://sonarcloud.io \
                                        -Dsonar.login=$SONAR_TOKEN
                                """
                        }
                    }     
                    }
                }
            }
        }

        stage("Set Docker Version") {
            steps {
                dir("backend") {
                    script {

                        // Read current version
                        def currentVersion = sh(
                            script: 'cat VERSION',
                            returnStdout: true
                        ).trim()

                        // Use current version for this Docker build
                        env.DOCKER_VERSION = currentVersion

                        echo "Docker Version: ${env.DOCKER_VERSION}"

                        // Calculate next version
                        def version = currentVersion.replace("v", "").split("\\.")

                        def major = version[0].toInteger()
                        def minor = version[1].toInteger()
                        def patch = version[2].toInteger()

                        patch++

                        def nextVersion = "v${major}.${minor}.${patch}"

                        // Save next version for the next build
                        sh """
                            echo "${nextVersion}" > VERSION
                        """

                        echo "Next Version: ${nextVersion}"
                    }
                }
            }
        }

        stage ("Docker Build") {
            // when {
            //     expression {false}
            // }
            steps {
                dir("backend") {
                    sh '''
                        echo "Building backend Docker image: $DOCKER_VERSION"

                        docker compose build task-manager-backend

                        echo "Backend Docker image built successfully"
                        echo "Image: task-manager-backend:$DOCKER_VERSION"
                    '''
                }
            }
        }

        stage("Push Docker Image to ECR") {
            // when {
            //     expression {false}
            // }
            steps {
                dir("Backend") {
                    withCredentials([
                        string(
                            credentialsId: "AWS_ACCESS_KEY_ID",
                            variable: "AWS_ACCESS_KEY_ID"
                        ),
                        string(
                            credentialsId: "AWS_SECRET_ACCESS_KEY",
                            variable: "AWS_SECRET_ACCESS_KEY"
                        ),
                        string(
                            credentialsId: "AWS_ACCOUNT_ID",
                            variable: "AWS_ACCOUNT_ID"
                        ),
                        string(
                            credentialsId: "AWS_REGION",
                            variable: "AWS_REGION"
                        ),
                        string(
                            credentialsId: "AWS_REPOSITORY",
                            variable: "AWS_REPOSITORY"
                        )
                    ]) {
                        sh '''
                            echo "Logging into Amazon ECR"

                            ECR_REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

                            aws ecr get-login-password --region "$AWS_REGION" | \
                            docker login --username AWS --password-stdin "$ECR_REGISTRY"

                            echo "Tagging Backend Docker Image"

                            docker tag \
                                "task-manager-backend:$DOCKER_VERSION" \
                                "$ECR_REGISTRY/$AWS_REPOSITORY:$DOCKER_VERSION"

                            echo "Pushing Backend Docker Image"

                            docker push \
                                "$ECR_REGISTRY/$AWS_REPOSITORY:$DOCKER_VERSION"

                            echo "Backend Docker Image Successfully pushed to ECR"
                        '''
                    }
                }
            }
        }

        stage("Trivy Report") {
            steps {
                sh '''
                    wget -q https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl \
                        -O junit.tpl

                    echo "===== TRIVY VULNERABILITY SCAN ====="

                    trivy image \
                        --scanners vuln \
                        --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL \
                        task-manager-backend:$DOCKER_VERSION

                    echo "===== GENERATING JUNIT REPORT ====="

                    trivy image \
                        --scanners vuln \
                        --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL \
                        --format template \
                        --template "@junit.tpl" \
                        -o trivy-report.xml \
                        task-manager-backend:$DOCKER_VERSION
                '''
            }
        }

        stage("Checkout GitOps Repository") {
            steps {
                dir("backend-cd") {
                    git(
                        url: "https://github.com/opsbyNikhil/task-manager-backend-cd.git",
                        branch: "dev",
                        credentialsId: "task-manager-backend-cd-github"
                    )
                }
            }
        }
    }

    

    post {
        always {
            archiveArtifacts artifacts: 'trivy-report.xml', fingerprint: true
            junit allowEmptyResults: true, testResults: 'trivy-report.xml'
        }
    }


}