pipeline {
    environment {
        SECRET_KEY = credentials('task-manager-django-secret-key')
        RESEND_API_KEY = credentials('task-manager-resend-api-key')
        DB_PASSWORD = credentails('task-manager-db-password')
        task_manager_backend = "${BUILD_NUMBER}"
    }
    
    agent {
        label "task-manager"
    }
    
    triggers {
        pollSCM ("* * * * *")
    }

    stages {
        stage ("git checkout") {
            steps {
                git url: "https://github.com/opsbyNikhil/task-manager.git",
                    branch: "dev"
            }
        }

        stage ("Install Dependencies") {
            steps {
                dir ("backend") {
                    sh """
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    """
                }
            }
        }

        stage ("Run Tests") {
            steps {
                dir ("backend") {
                    withCredentials([
                        string(
                            credentialsId: 'SECRET_KEY',
                            variable: 'SECRET_KEY'
                        ),
                        string(
                            credentialsId: 'RESEND_API_KEY',
                            variable: 'RESEND_API_KEY'
                        ),
                    ]) 
                    {
                        withEnv([
                            'CORS_ALLOWED_ORIGINS=http://localhost:5173'
                        ]) {
                            sh """
                                if [ -z "$SECRET_KEY" ]; then
                                    echo "SECRET_KEY is NOT available"
                                    exit 1
                                else
                                    echo "SECRET_KEY is available"
                                fi

                                if [ -z "$RESEND_API_KEY" ]; then
                                    echo "RESEND_API_KEY is NOT available"
                                    exit 1
                                else
                                    echo "RESEND_API_KEY is available"
                                fi

                                . venv/bin/activate
                                python manage.py test
                            """
                        }    
                    }
                }
            }
        }

        stage ("Sonarqube scan") {
            steps {
                dir ("backend") {
                    withCredentials([
                        string(
                            credentialsId: "SONAR_ID",
                            variable: "SONAR_TOKEN"
                    )]){
                        script {
                            def scannerhome = tool "SONAR_ID"
                            withSonarQubeEnv("SONAR_ID") {
                                sh """
                                    ${scannerhome}/bin/sonar-scanner \
                                        -Dsonar.projectKey=opsbyNikhil_task-manager \
                                        -Dsonar.organization=opsbynikhil \
                                        -Dsonar.host.url=https://sonarcloud.io \
                                        -Dsonar.login=$SONAR_TOKEN
                                """
                        }
                    }     
                    }
                }
            }
        }

        stage ("Docker Image") {
            steps {
                dir ("backend") {
                    sh '''docker compose build task-manager-backend
                }
            }
        }



        // stage ("OWASP Dependency-Check") {
        //     steps {
        //         withCredentials ([
        //             string(
        //                 credentialsId: 'NVD_API_KEY', 
        //                 variable: 'NVD_API_KEY'
        //             )
        //         ]) {
        //             dir ("backend") {
        //                 sh """
        //                     dependency-check.sh \
        //                         --project "Task Manager Backend" \
        //                         --scan . \
        //                         --format HTML \
        //                         --out dependency-check-report \
        //                         --nvdApiKey "\$NVD_API_KEY" \
        //                         --failOnCVSS 7
        //                 """
        //             }
        //         }
        //     }
        // }


    }
}