apiVersion: v1
kind: Service
metadate:
  name: task-manager-frontend-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: task-manager-frontend-app
  ports:
    - port: 5173
      nodePort: 5173
      targetPort: 30012
      protocol: TCP