pipeline {
    
    agent {
        label "task-manager"
    }

    triggers {
        pollSCM("* * * * *")
    }

    stages {
        stage ("Git Checkout") {
            steps {
                git url: "https://github.com/opsbyNikhil/task-manager.git",
                    branch: "dev"
            }
        }

        stage ("Install Dependencies") {
            steps {
                dir ("frontend") {
                    sh """
                        npm install
                    """
                }
            }
        }

        stage ("Build Frontend") {
            steps {
                dir ("frontend") {
                    sh """
                        npm run build
                    """
                }
            }
        }
    }
}